name: Build Linux

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-24.04-arm
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest

    steps:

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libdav1d-dev

      - name: Install Rustup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add Target
        run: rustup target add ${{ matrix.target }}

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build
        run: cargo build --release --target=${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-binary
          path: target/${{ matrix.target }}/release/imagectl